### ISSUE TITLE
Failed to install on Solus

### ISSUE THREAD

**Issue by kz6fittycent** [diddlesnaps/cawbird#1]
I've tried a few times to install this on Solus and here's what I'm seeing:

```
james@ratchet ~ $ sudo snap install cawbird
2020-01-18T00:39:28-06:00 INFO snap "cawbird" has bad plugs or slots: audio-playback (unknown interface "audio-playback")
error: cannot perform the following tasks:
- Run install hook of "cawbird" snap if present (run hook "install": 
-----
+ exec /snap/cawbird/138/snap/command-chain/desktop-launch /snap/cawbird/138/bin/build-ld-cache
mkdir: cannot create directory '/run/user/0': Permission denied
+ mkdir -p /var/snap/cawbird/138/etc/ld.so.conf.d
+ cp -r '/etc/ld.so.conf.d/*' /var/snap/cawbird/138/etc/ld.so.conf.d
cp: cannot stat '/etc/ld.so.conf.d/*': No such file or directory
-----)
```

Any ideas?

**Comment by diddledan** [comment]
I think I've fixed this. Please try again :-) You likely need to run cawbird in a terminal to be able to login to twitter because the version of snapd on solus is too old to support opening the browser properly. The address is printed in the console if you run cawbird from terminal and click the "request pin" button.

**Comment by kz6fittycent** [comment]
That did it man! I installed the `edge` version and followed your directions. All good and even posted on Twitter about it.... :P
